# IPTV Source Registry
# Defines all M3U and EPG inputs used in the harmonization pipeline

sources:
  - name: m3u_US_primary
    type: m3u
    country: US
    url: "https://example.com/us_primary.m3u"
    decompress: false
    priority: 1
    enabled: true

  - name: m3u_CA_backup
    type: m3u
    country: CA
    url: "https://example.com/ca_backup.m3u"
    decompress: false
    priority: 2
    enabled: true

  - name: epg_US_main
    type: epg
    country: US
    url: "https://example.com/us_guide.xml.gz"
    decompress: true
    priority: 1
    enabled: true

  - name: epg_CA_alt
    type: epg
    country: CA
    url: "https://example.com/ca_guide.xml"
    decompress: false
    priority: 2
    enabled: true

  - name: m3u_UK_test
    type: m3u
    country: UK
    url: "https://example.com/uk_test.m3u"
    decompress: false
    priority: 3
    enabled: false  # Disabled for now

  - name: epg_FR_experimental
    type: epg
    country: FR
    url: "https://example.com/fr_exp.xml.gz"
    decompress: true
    priority: 3
    enabled: false  # Experimental source
